### PR TITLE
Implement option to hide invalid suggestions

### PR DESCRIPTION
**Pull request by auchri**
Hides suggestions which do not contain the query

See #658

### CODE REVIEW

**Comment by tkirda** [comment]
Invalid suggestions should be filtered out not hidden.

**Comment by auchri** [comment]
@tkirda But shouldn't this be part of the lib?

**Comment by tkirda** [comment]
If using client side filtering `lookupFilter` should be provided. If server side, then server should only return records that need to be displayed.

**Comment by auchri** [comment]
The readme says:

> By default it does partial string match (case insensitive)

So in that case, the other suggestions should be filtered out _by default_. Or am I wrong?

**Comment by tkirda** [comment]
Yes, when you provide source data as an array. When you provide a function, that function's responsibility is to do the filtering.

**Pull request closed without merging**
